version: '3.8'

services:
  api-service:
    build:
      context: .               # Root context to ensure file accessibility
      dockerfile: ./APICowMilk/Dockerfile  # Path to API Dockerfile
    container_name: api-cow-service
    environment:
      SQL_CONNECTION_STRING: "Server=conference-db;Database=Conference;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password1!"
    ports:
      - "8080:8080"
    networks:
      - conference-network
  mvc-service:
    build:
        context: .               # Root context to ensure file accessibility
        dockerfile: ./MVCCowMagic/Dockerfile  # Path to API Dockerfile
    container_name: mvc-cow-service
    environment:
      SQL_CONNECTION_STRING: "Server=conference-db;Database=Conference;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password1!"
    ports:
      - "80:80"
    networks:
      - conference-network     
       
networks:
  conference-network:
    driver: bridge

volumes:
  db_data: